from app.schemas import SkuDetail


MOCK_SKUS = [
    SkuDetail(
        sku_id="sku_athletic-tee-black-m",
        name="Athletic Tee / Black / M",
        vendor="Northstar Apparel",
        category="tops",
        price=32.0,
        cost=11.0,
        inventory=24,
        last_30_day_sales=120,
        last_7_day_sales=32,
        days_since_last_sale=0,
    ),
    SkuDetail(
        sku_id="sku_ribbed-tank-ivory-s",
        name="Ribbed Tank / Ivory / S",
        vendor="Coastal Basics",
        category="tops",
        price=28.0,
        cost=9.0,
        inventory=15,
        last_30_day_sales=90,
        last_7_day_sales=25,
        days_since_last_sale=1,
    ),
    SkuDetail(
        sku_id="sku_heritage-hoodie-charcoal-l",
        name="Heritage Hoodie / Charcoal / L",
        vendor="Summit Sportswear",
        category="outerwear",
        price=68.0,
        cost=24.0,
        inventory=9,
        last_30_day_sales=75,
        last_7_day_sales=20,
        days_since_last_sale=0,
        sku_lead_time_days=21,
    ),
    SkuDetail(
        sku_id="sku_crop-hoodie-rose-s",
        name="Crop Hoodie / Rose / S",
        vendor="Summit Sportswear",
        category="outerwear",
        price=62.0,
        cost=22.0,
        inventory=6,
        last_30_day_sales=66,
        last_7_day_sales=17,
        days_since_last_sale=0,
    ),
    SkuDetail(
        sku_id="sku_mesh-short-navy-l",
        name="Mesh Short / Navy / L",
        vendor="Harbor Goods",
        category="bottoms",
        price=36.0,
        cost=14.0,
        inventory=65,
        last_30_day_sales=78,
        last_7_day_sales=19,
        days_since_last_sale=1,
    ),
    SkuDetail(
        sku_id="sku_fleece-jogger-stone-m",
        name="Fleece Jogger / Stone / M",
        vendor="Harbor Goods",
        category="bottoms",
        price=54.0,
        cost=20.0,
        inventory=52,
        last_30_day_sales=45,
        last_7_day_sales=11,
        days_since_last_sale=2,
    ),
    SkuDetail(
        sku_id="sku_canvas-tote-olive",
        name="Canvas Tote / Olive",
        vendor="Atlas Carry",
        category="accessories",
        price=38.0,
        cost=13.0,
        inventory=210,
        last_30_day_sales=30,
        last_7_day_sales=8,
        days_since_last_sale=2,
    ),
    SkuDetail(
        sku_id="sku_wool-beanie-rust",
        name="Wool Beanie / Rust",
        vendor="Trailhead Accessories",
        category="accessories",
        price=24.0,
        cost=8.0,
        inventory=140,
        last_30_day_sales=18,
        last_7_day_sales=4,
        days_since_last_sale=7,
    ),
    SkuDetail(
        sku_id="sku_vintage-cap-forest",
        name="Vintage Cap / Forest",
        vendor="Civic Merch",
        category="accessories",
        price=30.0,
        cost=10.0,
        inventory=95,
        last_30_day_sales=12,
        last_7_day_sales=2,
        days_since_last_sale=12,
    ),
    SkuDetail(
        sku_id="sku_longline-tee-white-xl",
        name="Longline Tee / White / XL",
        vendor="Open Loom",
        category="specialty",
        price=34.0,
        cost=12.0,
        inventory=160,
        last_30_day_sales=6,
        last_7_day_sales=1,
        days_since_last_sale=23,
    ),
    SkuDetail(
        sku_id="sku_sherpa-vest-sand-xl",
        name="Sherpa Vest / Sand / XL",
        vendor="Peak Outerwear",
        category="outerwear",
        price=82.0,
        cost=34.0,
        inventory=48,
        last_30_day_sales=0,
        last_7_day_sales=0,
        days_since_last_sale=58,
    ),
    SkuDetail(
        sku_id="sku_archived-crew-sage-xs",
        name="Archived Crew / Sage / XS",
        vendor="Legacy Mills",
        category="archive",
        price=58.0,
        cost=21.0,
        inventory=74,
        last_30_day_sales=0,
        last_7_day_sales=0,
        days_since_last_sale=92,
    ),
]


def list_skus() -> list[SkuDetail]:
    return MOCK_SKUS


def get_sku(sku_id: str) -> SkuDetail | None:
    return next((sku for sku in MOCK_SKUS if sku.sku_id == sku_id), None)
