export type ChatReply = {
  answer: string;
  mode: "ai" | "local";
  model: string | null;
  fallback_reason: string | null;
  data_source: "db" | "mock";
  context_summary: string;
  related_links: { label: string; href: string }[];
};

export type InventoryChatMessage = {
  id: string;
  role: "user" | "assistant";
  content: string;
  status?: "sending" | "failed";
  error?: string;
  reply?: ChatReply;
  sample?: boolean;
};

export const CHAT_TIMEOUT_MS = 30_000;

export function parseChatReply(value: unknown): ChatReply {
  if (!value || typeof value !== "object") throw new Error("Invalid chat reply");
  const row = value as Record<string, unknown>;
  if (typeof row.answer !== "string" || !row.answer.trim() || row.answer.length > 20_000
    || (row.mode !== "ai" && row.mode !== "local") || (row.data_source !== "db" && row.data_source !== "mock")) {
    throw new Error("Invalid chat reply");
  }
  const links: ChatReply["related_links"] = [];
  for (const entry of Array.isArray(row.related_links) ? row.related_links : []) {
    if (!entry || typeof entry !== "object") continue;
    const { label, href } = entry as Record<string, unknown>;
    if (typeof label !== "string" || !label.trim() || typeof href !== "string"
      || !href.startsWith("/") || href.startsWith("//") || /[\\\u0000-\u0020]/.test(href)) continue;
    if (!links.some(link => link.href === href)) links.push({ label: label.slice(0, 100), href });
    if (links.length === 4) break;
  }
  return {
    answer: row.answer.trim(), mode: row.mode, data_source: row.data_source,
    model: row.mode === "ai" && typeof row.model === "string" && row.model.trim() ? row.model.trim().slice(0, 100) : null,
    fallback_reason: typeof row.fallback_reason === "string" ? row.fallback_reason : null,
    context_summary: typeof row.context_summary === "string" ? row.context_summary.slice(0, 500) : "",
    related_links: links,
  };
}

export function chatReplyLabel(reply: ChatReply): string {
  if (reply.mode === "local") return "Local inventory summary";
  if (reply.model === "gpt-5.6-luna") return "Luna";
  return reply.model || "Model reply · model not reported";
}

export function chatFallbackExplanation(reply: ChatReply): string | null {
  if (reply.mode !== "local") return null;
  switch (reply.fallback_reason) {
    case "disabled": case "missing_api_key": case "budget_disabled": case "invalid_configuration":
      return "Model replies are not enabled for this chat. This reply uses Skubase’s inventory rules.";
    case "global_budget_exhausted": case "shop_budget_exhausted": case "shop_rate_limited":
      return "Model usage is currently limited. This reply uses Skubase’s inventory rules.";
    case "provider_unavailable": case "invalid_response": case "budget_unavailable":
      return "A model reply was unavailable. This reply uses Skubase’s inventory rules.";
    case "insufficient_data":
      return "More usable inventory data is needed. This reply explains the available inventory signals.";
    case "context_too_large":
      return "The inventory context is too large for a model reply. This reply uses a local summary.";
    default:
      return "This reply uses Skubase’s inventory rules; it was not generated by a language model.";
  }
}

export function chatRequestMessages(messages: InventoryChatMessage[]) {
  return messages.filter(message => message.id !== "welcome" && message.status !== "failed")
    .slice(-10).map(({ role, content }) => ({ role, content: content.slice(0, 2000) }));
}

export function chatErrorCopy(status?: number): string {
  if (status === 401) return "Your session expired. Sign in again, then retry your question.";
  if (status === 402 || status === 403) return "Chat access could not be confirmed. Review your account, then retry.";
  if (status === 422) return "This question could not be processed. Edit or shorten it, then try again.";
  if (status === 429) return "Chat is busy. Wait a moment, then retry your question.";
  return "Ask Skubase could not answer right now. Retry your question in a moment.";
}

type TextBlock = { kind: "paragraph" | "ordered" | "unordered" | "heading"; lines: string[] };
export function chatTextBlocks(text: string): TextBlock[] {
  const blocks: TextBlock[] = [];
  let separated = true;
  for (const raw of text.replace(/\r\n/g, "\n").split("\n")) {
    const line = raw.trim();
    if (!line) { separated = true; continue; }
    const kind: TextBlock["kind"] = /^\d+[.)]\s+/.test(line) ? "ordered"
      : /^[-*]\s+/.test(line) ? "unordered" : /^#{1,3}\s+/.test(line) ? "heading" : "paragraph";
    const clean = line.replace(/^(?:\d+[.)]|[-*]|#{1,3})\s+/, "");
    const previous = blocks[blocks.length - 1];
    if (!separated && previous?.kind === kind && kind !== "heading") previous.lines.push(clean);
    else blocks.push({ kind, lines: [clean] });
    separated = false;
  }
  return blocks;
}
